### PR TITLE
AvailabilitySelector component

### LINKED ISSUE #44: React component for choosing availability time ranges
Availability data is stored as a "Y" or "N" for each hour of the UTC day.

Let's build a React component to display and edit this value, in a way that's natural for the user.  Natural might mean in their own timezone, and easily selecting a range of times.  But complicating factors are that the Y's an N's are on UTC hour boundaries, and timezones like India's and Newfoundland's are not aligned with those hours; and that some people may want to select discontiguous ranges of time (e.g., some folks work an early-morning shift and a late-evening shift, locally, to allow overlap with co-workers).

### PR DESCRIPTION
**Pull request by djmitche**
A Material-style component to allow selecting times of day that a person is available, fixing #44.

image

image

@sarah-clements, this is still a draft, but I'd like to get your review. Specifically:
 * The "custom" switch hides its label at a small size, deferring to the tooltip.  But I think tooltips don't work on touch devices anyway, so this leaves users staring at an un-labeled control.  Ideas?
 * Similarly, the "custom" view is completely un-labeled, except for tooltips.  What would be a good, but small-screen-compatible, way to make this view usable?
 * I seem to be failing at flexbox in the custom view.  The image above shows 18 hours on one row and 6 on the next, and that's just really horrible.  I will keep futzing with that once I've got a plan for the previous point, but if you see an obvious fix I'm interested :)

Still to do:
 * offset back and forth from the user's timezone to UTC
 * include the name of the user's timezone, if available, in the caption

### CODE REVIEW

**Comment by sarah-clements** [comment]
> A Material-style component to allow selecting times of day that a person is available, fixing #44.
> 
> image
> 
> image
> 
> @sarah-clements, this is still a draft, but I'd like to get your review. Specifically:
> 
>  * The "custom" switch hides its label at a small size, deferring to the tooltip.  But I think tooltips don't work on touch devices anyway, so this leaves users staring at an un-labeled control.  Ideas?

>  * Similarly, the "custom" view is completely un-labeled, except for tooltips.  What would be a good, but small-screen-compatible, way to make this view usable?

How about changing it to a button that will toggle a separate component below it when clicked (and then close it when clicked again)? Then that separate panel could have the time slots stacked vertically like this (i grabbed this from timeanddate.com):

Screen Shot 2021-01-28 at 3 02 34 PM

The color coding of yellow for "as necessary" ("If I must"?) and green for "preferred" for available could be useful, but maybe that'd add too much complexity. :) I wonder if it'd help to show a full 5 days like this in case some people have preferences for specific days.

**Comment by sarah-clements** [comment]
When a user moves one of the slides, does it change by the minute or the hour? Cause if its by the hour or half hour, two dropdown menus for start and end would also work.

**Comment by djmitche** [comment]
image
image

I'm pretty happy with this -- it looks nice on the "small mobile" view, even if the slider is a little narrow.  And the side-by-side "custom" view extends to stack vertically on the "small mobile" view.

**Comment by djmitche** [comment]
I think this is completely implemented now -- it handles timezone offsets, which was the last missing feature.

Note that you can see this in action with just `yarn; yarn storybook` in the `frontend/` directory, without any of the Python stuff.

**Comment by djmitche** [comment]
@sarah-clements I can't flag you for review, but if you don't mind having another look I'd appreciate it.

We discussed a little in chat, but to put it here: the goal is to make a simple tool for general availability to help us pair people, and let participants negotiate the actual scheduling of meetings.  The pairing view will have some kind of indication of how much overlap two people have.  So we don't get into days of the week, or good/bad times, or even fractional hours.

**Comment by djmitche** [comment]
(Note that the "Controlled Value" bit is displayed by the storybook, not part of the component)

**Comment by sarah-clements** [comment]
> @sarah-clements I can't flag you for review, but if you don't mind having another look I'd appreciate it.
> 
> We discussed a little in chat, but to put it here: the goal is to make a simple tool for general availability to help us pair people, and let participants negotiate the actual scheduling of meetings. The pairing view will have some kind of indication of how much overlap two people have. So we don't get into days of the week, or good/bad times, or even fractional hours.

One consideration could be to not show any of the hours in the customize section that are outside of the range people select on the slider since if someone is selecting 8am as the top of the range, they likely aren't going to select 3am as an available time slot :)  But overall, this looks a lot clearer.

**Comment by djmitche** [comment]
> One consideration could be to not show any of the hours in the customize section that are outside of the range people select on the slider since if someone is selecting 8am as the top of the range, they likely aren't going to select 3am as an available time slot :) But overall, this looks a lot clearer.

Ah, so the "custom" part is in addition to the slider, and allows selecting specific hours within that time.  My worry is that someone will not see the link between "why isn't there a 7am option" and the slider starting at 8am.  But with both visible, maybe that's clear enough?  I suppose that'd be a good case for user testing in a larger project :)

I'll land this as-is (with lint fixed), since the enrollment form is depending on it, and move the suggestion to an issue.

**Comment by sarah-clements** [comment]
> > One consideration could be to not show any of the hours in the customize section that are outside of the range people select on the slider since if someone is selecting 8am as the top of the range, they likely aren't going to select 3am as an available time slot :) But overall, this looks a lot clearer.
> 
> Ah, so the "custom" part is in addition to the slider, and allows selecting specific hours within that time. My worry is that someone will not see the link between "why isn't there a 7am option" and the slider starting at 8am. But with both visible, maybe that's clear enough? I suppose that'd be a good case for user testing in a larger project :)

Yes, exactly. This does sound like a good thing to test with a user, ie ask someone to fill out the form as you watch them or ask for feedback on what parts were unclear and didn't flow well. :)

**Pull request merged**
