### PR TITLE
Build a docker image for deployment.

### PR DESCRIPTION
**Pull request by djmitche**
@the-smooth-operator I've added some docs of the environment variables to set in the README.  What do you think - what's missing?

### CODE REVIEW

**Comment by the-smooth-operator** [comment]
This looks very good to me.
I was unable to find the configuration for the Production class database in the project settings.py

This afternoon, I'm going to test deploying the project and come back with my findings.

**Comment by djmitche** [comment]
Good point. I expect there are a number of prod settings missing..

Dustin

**Comment by the-smooth-operator** [comment]
I could run the app in Development mode from docker and it looks fine.

I guess a part of some conf values missing from Production configuration, the only other thing I'm missing for Production would be to run gunicorn or some other application server instead of the one integrated with Django.
However we don't need to do this right now.

**Comment by djmitche** [comment]
Regarding gunicorn, that's a good point.. do you have an example I could copy from? :)

**Comment by djmitche** [comment]
I'll get this merged as a step along the way, and open some more issues for next steps.

**Comment by the-smooth-operator** [comment]
> Regarding gunicorn, that's a good point.. do you have an example I could copy from? :)

Yes, this is a pretty old example but I think still relevant: https://github.com/mozilla/mozmoderator/blob/master/bin/run-prod.sh

Here instead of having a single command defined in the Dockerfile we are calling a script which migrates+collecstatic+starts-server with gunircorn

**Pull request merged**
